services:
    wallabag_user.auth_code_mailer:
        class: Wallabag\UserBundle\Mailer\AuthCodeMailer
        arguments:
            - "@mailer"
            - "@twig"
            - "%scheb_two_factor.email.sender_email%"
            - "%scheb_two_factor.email.sender_name%"
            - "@craue_config"

    wallabag_user.password_resetting:
        class: Wallabag\UserBundle\EventListener\PasswordResettingListener
        arguments:
            - "@router"
        tags:
            - { name: kernel.event_subscriber }

    wallabag_user.user_repository:
        class: Wallabag\UserBundle\Repository\UserRepository
        factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
        arguments:
            - WallabagUserBundle:User
